modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${version}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="noeppi_noeppi"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.20.1-5.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.20.1-3.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jei"
    mandatory=false
    versionRange="[15.2.0.27,)"
    side="BOTH"

[[dependencies.bongo]]
    modId="jade"
    mandatory=false
    versionRange="[11.7.1,)"
    ordering="NONE"
    side="BOTH"

