modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
updateJSONURL="https://assets.melanx.de/updates/bongo.json"
authors="noeppi_noeppi"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.1-4.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="skyblockbuilder"
    mandatory=false
    versionRange="[1.19.1-4.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minemention"
    mandatory=false
    versionRange="[1.19.1-2.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jei"
    mandatory=false
    versionRange="[11.2.0.256,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="jade"
    mandatory=false
    versionRange="[8.0.1,)"
    ordering="NONE"
    side="BOTH"

